{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "91654b98",
   "metadata": {
    "_cell_guid": "29e03169-88d3-4f63-a7da-f34ae0eb3db0",
    "_uuid": "22e946c8-8912-4165-86f7-6fca72dacd53",
    "collapsed": false,
    "execution": {
     "iopub.execute_input": "2026-03-09T22:09:51.654584Z",
     "iopub.status.busy": "2026-03-09T22:09:51.653826Z",
     "iopub.status.idle": "2026-03-09T22:10:14.326176Z",
     "shell.execute_reply": "2026-03-09T22:10:14.325568Z"
    },
    "jupyter": {
     "outputs_hidden": false
    },
    "papermill": {
     "duration": 22.678411,
     "end_time": "2026-03-09T22:10:14.327791",
     "exception": false,
     "start_time": "2026-03-09T22:09:51.649380",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "# IMPORTING LIBRARIES\n",
    "\n",
    "import os\n",
    "import random\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "import torchaudio\n",
    "import torchaudio.transforms as T\n",
    "import soundfile as sf\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "from sklearn.metrics import f1_score\n",
    "from tqdm import tqdm\n",
    "from transformers import HubertModel, Wav2Vec2FeatureExtractor\n",
    "from torch.cuda.amp import GradScaler, autocast"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "331f6e1c",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2026-03-09T22:10:14.332447Z",
     "iopub.status.busy": "2026-03-09T22:10:14.331947Z",
     "iopub.status.idle": "2026-03-09T22:10:14.342272Z",
     "shell.execute_reply": "2026-03-09T22:10:14.341707Z"
    },
    "papermill": {
     "duration": 0.014025,
     "end_time": "2026-03-09T22:10:14.343631",
     "exception": false,
     "start_time": "2026-03-09T22:10:14.329606",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "# CONFIGURATION\n",
    "\n",
    "class CFG:\n",
    "    DATA_ROOT = \"/kaggle/input/jan-2026-dl-gen-ai-project/messy_mashup\"\n",
    "    \n",
    "    MODEL_NAME = \"facebook/hubert-base-ls960\"\n",
    "    GENRES = ['blues','classical','country','disco','hiphop',\n",
    "              'jazz','metal','pop','reggae','rock']\n",
    "    STEM_KEYS = ['drums','vocals','bass','other']\n",
    "\n",
    "    SR = 16000\n",
    "    DURATION = 5\n",
    "    BATCH_SIZE = 16 \n",
    "    EPOCHS = 10     \n",
    "    LR_BACKBONE = 2e-5\n",
    "    LR_HEAD = 1e-4\n",
    "    WEIGHT_DECAY = 0.05\n",
    "    SEED = 42 \n",
    "    \n",
    "\n",
    "DEVICE = torch.device(\"cuda\" if torch.cuda.is_available() else \"mps\" if torch.backends.mps.is_available() else \"cpu\")\n",
    "\n",
    "def seed_everything(seed):\n",
    "    random.seed(seed)\n",
    "    np.random.seed(seed)\n",
    "    torch.manual_seed(seed)\n",
    "    torch.cuda.manual_seed(seed)\n",
    "    torch.backends.cudnn.deterministic = True\n",
    "\n",
    "seed_everything(CFG.SEED)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "026840f1",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2026-03-09T22:10:14.347854Z",
     "iopub.status.busy": "2026-03-09T22:10:14.347429Z",
     "iopub.status.idle": "2026-03-09T22:10:14.353400Z",
     "shell.execute_reply": "2026-03-09T22:10:14.352659Z"
    },
    "papermill": {
     "duration": 0.009599,
     "end_time": "2026-03-09T22:10:14.354776",
     "exception": false,
     "start_time": "2026-03-09T22:10:14.345177",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "# DATASET BUILDER\n",
    "\n",
    "def build_dataset(root_dir, val_split=0.15):\n",
    "    train_samples, val_samples = [], []\n",
    "    base = os.path.join(root_dir, \"genres_stems\")\n",
    "\n",
    "    for genre_idx, genre in enumerate(CFG.GENRES):\n",
    "        genre_dir = os.path.join(base, genre)\n",
    "        if not os.path.isdir(genre_dir): continue\n",
    "        \n",
    "        songs = sorted(os.listdir(genre_dir))\n",
    "        random.shuffle(songs)\n",
    "        split = int(len(songs)*(1-val_split))\n",
    "\n",
    "        for i, song in enumerate(songs):\n",
    "            stem_paths = {s: os.path.join(genre_dir, song, f\"{s}.wav\") for s in CFG.STEM_KEYS}\n",
    "            stem_paths = {k: v for k, v in stem_paths.items() if os.path.exists(v)}\n",
    "            \n",
    "            if len(stem_paths) == len(CFG.STEM_KEYS):\n",
    "                sample = (genre_idx, stem_paths)\n",
    "                if i < split: train_samples.append(sample)\n",
    "                else: val_samples.append(sample)\n",
    "\n",
    "    return train_samples, val_samples"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "160d51d7",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2026-03-09T22:10:14.359083Z",
     "iopub.status.busy": "2026-03-09T22:10:14.358505Z",
     "iopub.status.idle": "2026-03-09T22:10:14.366527Z",
     "shell.execute_reply": "2026-03-09T22:10:14.365773Z"
    },
    "papermill": {
     "duration": 0.011593,
     "end_time": "2026-03-09T22:10:14.367931",
     "exception": false,
     "start_time": "2026-03-09T22:10:14.356338",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "# DARASET CLASS\n",
    "\n",
    "class MusicDataset(Dataset):\n",
    "    def __init__(self, samples, augment=True):\n",
    "        self.samples = samples\n",
    "        self.augment = augment\n",
    "        self.target_samples = CFG.SR * CFG.DURATION\n",
    "        self.resampler = None \n",
    "\n",
    "    def load_audio(self, path):\n",
    "        wav, sr = sf.read(path)\n",
    "        wav = torch.from_numpy(wav).float()\n",
    "        \n",
    "        if len(wav.shape) > 1:\n",
    "            wav = torch.mean(wav, dim=1, keepdim=True).T\n",
    "        else:\n",
    "            wav = wav.unsqueeze(0)\n",
    "            \n",
    "        if sr != CFG.SR:\n",
    "            resampler = T.Resample(sr, CFG.SR)\n",
    "            wav = resampler(wav)\n",
    "            \n",
    "        return wav.squeeze(0)\n",
    "\n",
    "    def __len__(self):\n",
    "        return len(self.samples)\n",
    "\n",
    "    def __getitem__(self, idx):\n",
    "        label, stems = self.samples[idx]\n",
    "        mix = torch.zeros(self.target_samples)\n",
    "\n",
    "        for stem in CFG.STEM_KEYS:\n",
    "            y = self.load_audio(stems[stem])\n",
    "            \n",
    "            if y.shape[0] > self.target_samples:\n",
    "                if not self.augment: \n",
    "                    start = (y.shape[0] - self.target_samples) // 2\n",
    "                else:\n",
    "                    start = random.randint(0, y.shape[0] - self.target_samples)\n",
    "                y = y[start : start + self.target_samples]\n",
    "            else:\n",
    "                y = torch.nn.functional.pad(y, (0, self.target_samples - y.shape[0]))\n",
    "\n",
    "            rms = torch.sqrt(torch.mean(y**2) + 1e-9)\n",
    "            y = y / rms\n",
    "            \n",
    "            vol = random.uniform(0.4, 1.1) if self.augment else 0.8\n",
    "            mix += y * vol\n",
    "\n",
    "        mix = mix / (torch.max(torch.abs(mix)) + 1e-6)\n",
    "\n",
    "        if self.augment:\n",
    "            mix += torch.randn_like(mix) * 0.002\n",
    "\n",
    "        return mix, label\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "f1a8045b",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2026-03-09T22:10:14.372117Z",
     "iopub.status.busy": "2026-03-09T22:10:14.371557Z",
     "iopub.status.idle": "2026-03-09T22:10:14.377966Z",
     "shell.execute_reply": "2026-03-09T22:10:14.377062Z"
    },
    "papermill": {
     "duration": 0.010102,
     "end_time": "2026-03-09T22:10:14.379502",
     "exception": false,
     "start_time": "2026-03-09T22:10:14.369400",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [],
   "source": [
    "# HUBERT\n",
    "\n",
    "class HubertClassifier(nn.Module):\n",
    "    def __init__(self, num_classes=10):\n",
    "        super().__init__()\n",
    "        self.hubert = HubertModel.from_pretrained(CFG.MODEL_NAME)\n",
    "        \n",
    "        for layer in self.hubert.encoder.layers[:6]:\n",
    "            for p in layer.parameters():\n",
    "                p.requires_grad = False\n",
    "\n",
    "        self.gru = nn.GRU(\n",
    "            input_size=768,\n",
    "            hidden_size=384,\n",
    "            num_layers=2,\n",
    "            batch_first=True,\n",
    "            dropout=0.3,\n",
    "            bidirectional=True\n",
    "        )\n",
    "\n",
    "        self.attn = nn.Sequential(\n",
    "            nn.Linear(768, 128),\n",
    "            nn.Tanh(),\n",
    "            nn.Linear(128, 1)\n",
    "        )\n",
    "\n",
    "        self.classifier = nn.Sequential(\n",
    "            nn.Linear(768, 256),\n",
    "            nn.BatchNorm1d(256),\n",
    "            nn.Dropout(0.4),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(256, num_classes)\n",
    "        )\n",
    "\n",
    "    def forward(self, x):\n",
    "        h = self.hubert(x).last_hidden_state\n",
    "        h, _ = self.gru(h)\n",
    "        \n",
    "        attn_weights = torch.softmax(self.attn(h), dim=1)\n",
    "        pooled = torch.sum(h * attn_weights, dim=1)\n",
    "        \n",
    "        return self.classifier(pooled)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "82b62419",
   "metadata": {
    "_kg_hide-output": false,
    "execution": {
     "iopub.execute_input": "2026-03-09T22:10:14.383491Z",
     "iopub.status.busy": "2026-03-09T22:10:14.383252Z",
     "iopub.status.idle": "2026-03-09T22:10:19.591138Z",
     "shell.execute_reply": "2026-03-09T22:10:19.590497Z"
    },
    "papermill": {
     "duration": 5.211895,
     "end_time": "2026-03-09T22:10:19.592840",
     "exception": false,
     "start_time": "2026-03-09T22:10:14.380945",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "658f2ac455c84d38aeedfb9552e6c5b1",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "preprocessor_config.json:   0%|          | 0.00/213 [00:00<?, ?B/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# TRAINING\n",
    "\n",
    "extractor = Wav2Vec2FeatureExtractor.from_pretrained(CFG.MODEL_NAME)\n",
    "\n",
    "def collate_fn(batch):\n",
    "    audio = [b[0].numpy() for b in batch]\n",
    "    labels = torch.tensor([b[1] for b in batch])\n",
    "    inputs = extractor(audio, sampling_rate=CFG.SR, padding=True, return_tensors=\"pt\")\n",
    "    return inputs.input_values, labels\n",
    "\n",
    "NUM_WORKERS = 4 if os.path.exists(CFG.DATA_ROOT) else 0\n",
    "PIN_MEMORY = True if os.path.exists(CFG.DATA_ROOT) else False\n",
    "\n",
    "train_samples, val_samples = build_dataset(CFG.DATA_ROOT)\n",
    "train_loader = DataLoader(MusicDataset(train_samples, True), batch_size=CFG.BATCH_SIZE, shuffle=True, collate_fn=collate_fn, num_workers=NUM_WORKERS, pin_memory=PIN_MEMORY, drop_last=True)\n",
    "val_loader = DataLoader(MusicDataset(val_samples, False), batch_size=CFG.BATCH_SIZE, shuffle=False, collate_fn=collate_fn, num_workers=NUM_WORKERS)\n",
    "\n",
    "def train_and_predict():\n",
    "    model = HubertClassifier(len(CFG.GENRES)).to(DEVICE)\n",
    "\n",
    "    optimizer = optim.AdamW([\n",
    "        {\"params\": model.hubert.parameters(), \"lr\": CFG.LR_BACKBONE, \"weight_decay\": CFG.WEIGHT_DECAY},\n",
    "        {\"params\": model.gru.parameters(), \"lr\": CFG.LR_HEAD, \"weight_decay\": CFG.WEIGHT_DECAY},\n",
    "        {\"params\": model.attn.parameters(), \"lr\": CFG.LR_HEAD, \"weight_decay\": 0.0},\n",
    "        {\"params\": model.classifier.parameters(), \"lr\": CFG.LR_HEAD, \"weight_decay\": CFG.WEIGHT_DECAY},\n",
    "    ])\n",
    "\n",
    "    scheduler = optim.lr_scheduler.OneCycleLR(\n",
    "        optimizer, max_lr=[CFG.LR_BACKBONE, CFG.LR_HEAD, CFG.LR_HEAD, CFG.LR_HEAD],\n",
    "        steps_per_epoch=len(train_loader), epochs=CFG.EPOCHS\n",
    "    )\n",
    "\n",
    "    criterion = nn.CrossEntropyLoss(label_smoothing=0.1)\n",
    "    use_amp = True if DEVICE.type == \"cuda\" else False\n",
    "    scaler = GradScaler() if use_amp else None\n",
    "\n",
    "    print(f\"Device: {DEVICE}\")\n",
    "    for epoch in range(CFG.EPOCHS):\n",
    "        model.train()\n",
    "        losses = []\n",
    "        for x, y in tqdm(train_loader, desc=f\"Epoch {epoch+1}/{CFG.EPOCHS}\"):\n",
    "            x, y = x.to(DEVICE), y.to(DEVICE)\n",
    "            optimizer.zero_grad()\n",
    "            if use_amp:\n",
    "                with autocast():\n",
    "                    out = model(x)\n",
    "                    loss = criterion(out, y)\n",
    "                scaler.scale(loss).backward()\n",
    "                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n",
    "                scaler.step(optimizer)\n",
    "                scaler.update()\n",
    "            else:\n",
    "                out = model(x)\n",
    "                loss = criterion(out, y)\n",
    "                loss.backward()\n",
    "                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n",
    "                optimizer.step()\n",
    "            \n",
    "            scheduler.step()\n",
    "            losses.append(loss.item())\n",
    "\n",
    "        model.eval()\n",
    "        preds, targets = [], []\n",
    "        with torch.no_grad():\n",
    "            for x, y in val_loader:\n",
    "                out = model(x.to(DEVICE))\n",
    "                preds.extend(torch.argmax(out, 1).cpu().numpy())\n",
    "                targets.extend(y.numpy())\n",
    "        \n",
    "        f1 = f1_score(targets, preds, average=\"macro\")\n",
    "        print(f\"Epoch {epoch+1}/{CFG.EPOCHS} | Loss: {np.mean(losses):.4f} | Val MacroF1: {f1:.4f}\")\n",
    "        torch.save(model.state_dict(), \"hubert_classifier.pth\")\n",
    "\n",
    "    test_df = pd.read_csv(os.path.join(CFG.DATA_ROOT, \"test.csv\"))\n",
    "    model.eval()\n",
    "    final_test_preds = []\n",
    "\n",
    "    for fname in tqdm(test_df[\"filename\"]):\n",
    "        wav, sr = sf.read(os.path.join(CFG.DATA_ROOT, fname))\n",
    "        wav = torch.from_numpy(wav).float()\n",
    "        if len(wav.shape) > 1: wav = wav.mean(1, keepdim=True).T\n",
    "        else: wav = wav.unsqueeze(0)\n",
    "        \n",
    "        if sr != CFG.SR:\n",
    "            wav = T.Resample(sr, CFG.SR)(wav)\n",
    "        wav = wav.squeeze(0)\n",
    "        \n",
    "        total_len = wav.shape[0]\n",
    "        target_len = CFG.SR * CFG.DURATION\n",
    "        \n",
    "        if total_len > target_len:\n",
    "            offsets = [0, (total_len-target_len)//4, (total_len-target_len)//2, \n",
    "                       3*(total_len-target_len)//4, total_len-target_len]\n",
    "            crops = [wav[o : o + target_len] for o in offsets]\n",
    "        else:\n",
    "            crops = [torch.nn.functional.pad(wav, (0, target_len - total_len))] * 5\n",
    "        \n",
    "        inputs = extractor(crops, sampling_rate=CFG.SR, padding=True, return_tensors=\"pt\").input_values.to(DEVICE)\n",
    "        if inputs.ndim == 3: inputs = inputs.squeeze(0) # [5, Time]\n",
    "        with torch.no_grad():\n",
    "            logits = model(inputs)\n",
    "            avg_probs = torch.softmax(logits, dim=1).mean(0)\n",
    "            final_test_preds.append(CFG.GENRES[avg_probs.argmax().item()])\n",
    "\n",
    "    pd.DataFrame({\"id\": test_df[\"id\"], \"genre\": final_test_preds}).to_csv(\"submission.csv\", index=False)\n",
    "    print(\"SUCCESS!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "9c58ba02",
   "metadata": {
    "execution": {
     "iopub.execute_input": "2026-03-09T22:10:19.598581Z",
     "iopub.status.busy": "2026-03-09T22:10:19.597824Z",
     "iopub.status.idle": "2026-03-09T22:32:19.015905Z",
     "shell.execute_reply": "2026-03-09T22:32:19.014974Z"
    },
    "papermill": {
     "duration": 1319.422852,
     "end_time": "2026-03-09T22:32:19.017691",
     "exception": false,
     "start_time": "2026-03-09T22:10:19.594839",
     "status": "completed"
    },
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "db417a9bf01e4ae9a9d419b88f55d497",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "config.json: 0.00B [00:00, ?B/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "696e5a15578e4c28a58180fa4fb06a63",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "pytorch_model.bin:   0%|          | 0.00/378M [00:00<?, ?B/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "5d32a0e05feb46f9a4aee780ce0c60b0",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "Loading weights:   0%|          | 0/211 [00:00<?, ?it/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "5bb1898cf53e4e9ca2a82c76515cbf01",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "model.safetensors:   0%|          | 0.00/378M [00:00<?, ?B/s]"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/tmp/ipykernel_24/2591604764.py:35: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.\n",
      "  scaler = GradScaler() if use_amp else None\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Device: cuda\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "Epoch 1/10:   0%|          | 0/53 [00:00<?, ?it/s]\u001b[A/tmp/ipykernel_24/2591604764.py:45: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.\n",
      "  with autocast():\n",
      "\n",
      "Epoch 1/10:   2%|▏         | 1/53 [00:10<09:15, 10.68s/it]\u001b[A\n",
      "Epoch 1/10:   4%|▍         | 2/53 [00:11<03:55,  4.61s/it]\u001b[A\n",
      "Epoch 1/10:   6%|▌         | 3/53 [00:11<02:14,  2.68s/it]\u001b[A\n",
      "Epoch 1/10:   8%|▊         | 4/53 [00:11<01:27,  1.78s/it]\u001b[A\n",
      "Epoch 1/10:   9%|▉         | 5/53 [00:15<02:04,  2.60s/it]\u001b[A\n",
      "Epoch 1/10:  11%|█▏        | 6/53 [00:16<01:26,  1.85s/it]\u001b[A\n",
      "Epoch 1/10:  13%|█▎        | 7/53 [00:16<01:02,  1.37s/it]\u001b[A\n",
      "Epoch 1/10:  15%|█▌        | 8/53 [00:17<00:47,  1.06s/it]\u001b[A\n",
      "Epoch 1/10:  17%|█▋        | 9/53 [00:22<01:52,  2.55s/it]\u001b[A\n",
      "Epoch 1/10:  19%|█▉        | 10/53 [00:23<01:21,  1.89s/it]\u001b[A\n",
      "Epoch 1/10:  21%|██        | 11/53 [00:23<01:00,  1.43s/it]\u001b[A\n",
      "Epoch 1/10:  23%|██▎       | 12/53 [00:24<00:45,  1.11s/it]\u001b[A\n",
      "Epoch 1/10:  25%|██▍       | 13/53 [00:29<01:41,  2.53s/it]\u001b[A\n",
      "Epoch 1/10:  26%|██▋       | 14/53 [00:30<01:13,  1.88s/it]\u001b[A\n",
      "Epoch 1/10:  28%|██▊       | 15/53 [00:30<00:54,  1.43s/it]\u001b[A\n",
      "Epoch 1/10:  30%|███       | 16/53 [00:31<00:41,  1.12s/it]\u001b[A\n",
      "Epoch 1/10:  32%|███▏      | 17/53 [00:36<01:33,  2.58s/it]\u001b[A\n",
      "Epoch 1/10:  34%|███▍      | 18/53 [00:37<01:07,  1.93s/it]\u001b[A\n",
      "Epoch 1/10:  36%|███▌      | 19/53 [00:37<00:50,  1.47s/it]\u001b[A\n",
      "Epoch 1/10:  38%|███▊      | 20/53 [00:38<00:38,  1.16s/it]\u001b[A\n",
      "Epoch 1/10:  40%|███▉      | 21/53 [00:43<01:20,  2.52s/it]\u001b[A\n",
      "Epoch 1/10:  42%|████▏     | 22/53 [00:44<00:58,  1.87s/it]\u001b[A\n",
      "Epoch 1/10:  43%|████▎     | 23/53 [00:44<00:42,  1.42s/it]\u001b[A\n",
      "Epoch 1/10:  45%|████▌     | 24/53 [00:45<00:32,  1.12s/it]\u001b[A\n",
      "Epoch 1/10:  47%|████▋     | 25/53 [00:51<01:12,  2.59s/it]\u001b[A\n",
      "Epoch 1/10:  49%|████▉     | 26/53 [00:51<00:52,  1.93s/it]\u001b[A\n",
      "Epoch 1/10:  51%|█████     | 27/53 [00:51<00:38,  1.47s/it]\u001b[A\n",
      "Epoch 1/10:  53%|█████▎    | 28/53 [00:52<00:28,  1.15s/it]\u001b[A\n",
      "Epoch 1/10:  55%|█████▍    | 29/53 [00:58<01:00,  2.54s/it]\u001b[A\n",
      "Epoch 1/10:  57%|█████▋    | 30/53 [00:58<00:43,  1.90s/it]\u001b[A\n",
      "Epoch 1/10:  58%|█████▊    | 31/53 [00:58<00:31,  1.45s/it]\u001b[A\n",
      "Epoch 1/10:  60%|██████    | 32/53 [00:59<00:23,  1.14s/it]\u001b[A\n",
      "Epoch 1/10:  62%|██████▏   | 33/53 [01:04<00:50,  2.50s/it]\u001b[A\n",
      "Epoch 1/10:  64%|██████▍   | 34/53 [01:05<00:35,  1.87s/it]\u001b[A\n",
      "Epoch 1/10:  66%|██████▌   | 35/53 [01:05<00:25,  1.42s/it]\u001b[A\n",
      "Epoch 1/10:  68%|██████▊   | 36/53 [01:06<00:19,  1.12s/it]\u001b[A\n",
      "Epoch 1/10:  70%|██████▉   | 37/53 [01:12<00:41,  2.60s/it]\u001b[A\n",
      "Epoch 1/10:  72%|███████▏  | 38/53 [01:12<00:29,  1.95s/it]\u001b[A\n",
      "Epoch 1/10:  74%|███████▎  | 39/53 [01:13<00:20,  1.49s/it]\u001b[A\n",
      "Epoch 1/10:  75%|███████▌  | 40/53 [01:13<00:15,  1.15s/it]\u001b[A\n",
      "Epoch 1/10:  77%|███████▋  | 41/53 [01:19<00:30,  2.55s/it]\u001b[A\n",
      "Epoch 1/10:  79%|███████▉  | 42/53 [01:19<00:20,  1.90s/it]\u001b[A\n",
      "Epoch 1/10:  81%|████████  | 43/53 [01:20<00:14,  1.45s/it]\u001b[A\n",
      "Epoch 1/10:  83%|████████▎ | 44/53 [01:20<00:10,  1.14s/it]\u001b[A\n",
      "Epoch 1/10:  85%|████████▍ | 45/53 [01:26<00:20,  2.58s/it]\u001b[A\n",
      "Epoch 1/10:  87%|████████▋ | 46/53 [01:26<00:13,  1.93s/it]\u001b[A\n",
      "Epoch 1/10:  89%|████████▊ | 47/53 [01:27<00:08,  1.48s/it]\u001b[A\n",
      "Epoch 1/10:  91%|█████████ | 48/53 [01:27<00:05,  1.15s/it]\u001b[A\n",
      "Epoch 1/10:  92%|█████████▏| 49/53 [01:33<00:10,  2.50s/it]\u001b[A\n",
      "Epoch 1/10:  94%|█████████▍| 50/53 [01:33<00:05,  1.88s/it]\u001b[A\n",
      "Epoch 1/10:  96%|█████████▌| 51/53 [01:34<00:02,  1.43s/it]\u001b[A\n",
      "Epoch 1/10:  98%|█████████▊| 52/53 [01:34<00:01,  1.12s/it]\u001b[A\n",
      "Epoch 1/10: 100%|██████████| 53/53 [01:39<00:00,  1.87s/it]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/10 | Loss: 2.3901 | Val MacroF1: 0.1214\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Epoch 2/10:   0%|          | 0/53 [00:00<?, ?it/s]/tmp/ipykernel_24/2591604764.py:45: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.\n",
      "  with autocast():\n",
      "Epoch 2/10: 100%|██████████| 53/53 [00:55<00:00,  1.05s/it]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 2/10 | Loss: 2.1964 | Val MacroF1: 0.3651\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Epoch 3/10:   0%|          | 0/53 [00:00<?, ?it/s]/tmp/ipykernel_24/2591604764.py:45: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.\n",
      "  with autocast():\n",
      "Epoch 3/10: 100%|██████████| 53/53 [00:55<00:00,  1.05s/it]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 3/10 | Loss: 1.8883 | Val MacroF1: 0.4156\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Epoch 4/10:   0%|          | 0/53 [00:00<?, ?it/s]/tmp/ipykernel_24/2591604764.py:45: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.\n",
      "  with autocast():\n",
      "Epoch 4/10: 100%|██████████| 53/53 [00:55<00:00,  1.04s/it]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 4/10 | Loss: 1.7326 | Val MacroF1: 0.4942\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Epoch 5/10:   0%|          | 0/53 [00:00<?, ?it/s]/tmp/ipykernel_24/2591604764.py:45: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.\n",
      "  with autocast():\n",
      "Epoch 5/10: 100%|██████████| 53/53 [00:55<00:00,  1.04s/it]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 5/10 | Loss: 1.6241 | Val MacroF1: 0.4408\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Epoch 6/10:   0%|          | 0/53 [00:00<?, ?it/s]/tmp/ipykernel_24/2591604764.py:45: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.\n",
      "  with autocast():\n",
      "Epoch 6/10: 100%|██████████| 53/53 [00:55<00:00,  1.04s/it]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 6/10 | Loss: 1.6144 | Val MacroF1: 0.5366\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Epoch 7/10:   0%|          | 0/53 [00:00<?, ?it/s]/tmp/ipykernel_24/2591604764.py:45: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.\n",
      "  with autocast():\n",
      "Epoch 7/10: 100%|██████████| 53/53 [00:54<00:00,  1.04s/it]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 7/10 | Loss: 1.5536 | Val MacroF1: 0.5401\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Epoch 8/10:   0%|          | 0/53 [00:00<?, ?it/s]/tmp/ipykernel_24/2591604764.py:45: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.\n",
      "  with autocast():\n",
      "Epoch 8/10: 100%|██████████| 53/53 [00:55<00:00,  1.04s/it]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 8/10 | Loss: 1.5347 | Val MacroF1: 0.5158\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Epoch 9/10:   0%|          | 0/53 [00:00<?, ?it/s]/tmp/ipykernel_24/2591604764.py:45: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.\n",
      "  with autocast():\n",
      "Epoch 9/10: 100%|██████████| 53/53 [00:55<00:00,  1.04s/it]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 9/10 | Loss: 1.5039 | Val MacroF1: 0.5405\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Epoch 10/10:   0%|          | 0/53 [00:00<?, ?it/s]/tmp/ipykernel_24/2591604764.py:45: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.\n",
      "  with autocast():\n",
      "Epoch 10/10: 100%|██████████| 53/53 [00:55<00:00,  1.05s/it]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 10/10 | Loss: 1.5089 | Val MacroF1: 0.5199\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 3020/3020 [09:52<00:00,  5.10it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "SUCCESS!\n"
     ]
    }
   ],
   "source": [
    "train_and_predict()"
   ]
  }
 ],
 "metadata": {
  "kaggle": {
   "accelerator": "nvidiaTeslaT4",
   "dataSources": [
    {
     "databundleVersionId": 15477148,
     "sourceId": 128431,
     "sourceType": "competition"
    }
   ],
   "isGpuEnabled": true,
   "isInternetEnabled": true,
   "language": "python",
   "sourceType": "notebook"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  },
  "papermill": {
   "default_parameters": {},
   "duration": 1352.861371,
   "end_time": "2026-03-09T22:32:22.142223",
   "environment_variables": {},
   "exception": null,
   "input_path": "__notebook__.ipynb",
   "output_path": "__notebook__.ipynb",
   "parameters": {},
   "start_time": "2026-03-09T22:09:49.280852",
   "version": "2.6.0"
  },
  "widgets": {
   "application/vnd.jupyter.widget-state+json": {
    "state": {
     "012e60fe92c441d1ab34f78af747a4b9": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HTMLStyleModel",
      "state": {
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HTMLStyleModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "StyleView",
       "background": null,
       "description_width": "",
       "font_size": null,
       "text_color": null
      }
     },
     "05bbd17994084c1995de3afe28122a29": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "2.0.0",
      "model_name": "LayoutModel",
      "state": {
       "_model_module": "@jupyter-widgets/base",
       "_model_module_version": "2.0.0",
       "_model_name": "LayoutModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "LayoutView",
       "align_content": null,
       "align_items": null,
       "align_self": null,
       "border_bottom": null,
       "border_left": null,
       "border_right": null,
       "border_top": null,
       "bottom": null,
       "display": null,
       "flex": null,
       "flex_flow": null,
       "grid_area": null,
       "grid_auto_columns": null,
       "grid_auto_flow": null,
       "grid_auto_rows": null,
       "grid_column": null,
       "grid_gap": null,
       "grid_row": null,
       "grid_template_areas": null,
       "grid_template_columns": null,
       "grid_template_rows": null,
       "height": null,
       "justify_content": null,
       "justify_items": null,
       "left": null,
       "margin": null,
       "max_height": null,
       "max_width": null,
       "min_height": null,
       "min_width": null,
       "object_fit": null,
       "object_position": null,
       "order": null,
       "overflow": null,
       "padding": null,
       "right": null,
       "top": null,
       "visibility": null,
       "width": "20px"
      }
     },
     "068ae19c5332403590ab54780985df67": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "2.0.0",
      "model_name": "LayoutModel",
      "state": {
       "_model_module": "@jupyter-widgets/base",
       "_model_module_version": "2.0.0",
       "_model_name": "LayoutModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "LayoutView",
       "align_content": null,
       "align_items": null,
       "align_self": null,
       "border_bottom": null,
       "border_left": null,
       "border_right": null,
       "border_top": null,
       "bottom": null,
       "display": null,
       "flex": null,
       "flex_flow": null,
       "grid_area": null,
       "grid_auto_columns": null,
       "grid_auto_flow": null,
       "grid_auto_rows": null,
       "grid_column": null,
       "grid_gap": null,
       "grid_row": null,
       "grid_template_areas": null,
       "grid_template_columns": null,
       "grid_template_rows": null,
       "height": null,
       "justify_content": null,
       "justify_items": null,
       "left": null,
       "margin": null,
       "max_height": null,
       "max_width": null,
       "min_height": null,
       "min_width": null,
       "object_fit": null,
       "object_position": null,
       "order": null,
       "overflow": null,
       "padding": null,
       "right": null,
       "top": null,
       "visibility": null,
       "width": null
      }
     },
     "0aa9b6ed35ab42708f124060d7a5d472": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HTMLModel",
      "state": {
       "_dom_classes": [],
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HTMLModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/controls",
       "_view_module_version": "2.0.0",
       "_view_name": "HTMLView",
       "description": "",
       "description_allow_html": false,
       "layout": "IPY_MODEL_da531c7308bd47f4af5c8aa32f0e1ed5",
       "placeholder": "​",
       "style": "IPY_MODEL_2c069abb5dfa414bbde130ae6532d054",
       "tabbable": null,
       "tooltip": null,
       "value": "pytorch_model.bin: 100%"
      }
     },
     "0d6ad60046a248d7b1948f815f2d0cd1": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "2.0.0",
      "model_name": "LayoutModel",
      "state": {
       "_model_module": "@jupyter-widgets/base",
       "_model_module_version": "2.0.0",
       "_model_name": "LayoutModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "LayoutView",
       "align_content": null,
       "align_items": null,
       "align_self": null,
       "border_bottom": null,
       "border_left": null,
       "border_right": null,
       "border_top": null,
       "bottom": null,
       "display": null,
       "flex": null,
       "flex_flow": null,
       "grid_area": null,
       "grid_auto_columns": null,
       "grid_auto_flow": null,
       "grid_auto_rows": null,
       "grid_column": null,
       "grid_gap": null,
       "grid_row": null,
       "grid_template_areas": null,
       "grid_template_columns": null,
       "grid_template_rows": null,
       "height": null,
       "justify_content": null,
       "justify_items": null,
       "left": null,
       "margin": null,
       "max_height": null,
       "max_width": null,
       "min_height": null,
       "min_width": null,
       "object_fit": null,
       "object_position": null,
       "order": null,
       "overflow": null,
       "padding": null,
       "right": null,
       "top": null,
       "visibility": null,
       "width": null
      }
     },
     "1966f6ac24e54cf78ef5b7c0b1e3c99e": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "2.0.0",
      "model_name": "LayoutModel",
      "state": {
       "_model_module": "@jupyter-widgets/base",
       "_model_module_version": "2.0.0",
       "_model_name": "LayoutModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "LayoutView",
       "align_content": null,
       "align_items": null,
       "align_self": null,
       "border_bottom": null,
       "border_left": null,
       "border_right": null,
       "border_top": null,
       "bottom": null,
       "display": null,
       "flex": null,
       "flex_flow": null,
       "grid_area": null,
       "grid_auto_columns": null,
       "grid_auto_flow": null,
       "grid_auto_rows": null,
       "grid_column": null,
       "grid_gap": null,
       "grid_row": null,
       "grid_template_areas": null,
       "grid_template_columns": null,
       "grid_template_rows": null,
       "height": null,
       "justify_content": null,
       "justify_items": null,
       "left": null,
       "margin": null,
       "max_height": null,
       "max_width": null,
       "min_height": null,
       "min_width": null,
       "object_fit": null,
       "object_position": null,
       "order": null,
       "overflow": null,
       "padding": null,
       "right": null,
       "top": null,
       "visibility": null,
       "width": null
      }
     },
     "1c877983bd7e49109a9c1d489252b12e": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "FloatProgressModel",
      "state": {
       "_dom_classes": [],
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "FloatProgressModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/controls",
       "_view_module_version": "2.0.0",
       "_view_name": "ProgressView",
       "bar_style": "success",
       "description": "",
       "description_allow_html": false,
       "layout": "IPY_MODEL_5afb47cb39524d9d83517894d66ed0fe",
       "max": 377569754.0,
       "min": 0.0,
       "orientation": "horizontal",
       "style": "IPY_MODEL_c85fa0d3c14f41febebbd370c9afbc0a",
       "tabbable": null,
       "tooltip": null,
       "value": 377569754.0
      }
     },
     "1d58b7b4dd574e148a45db40bfa05ac7": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "FloatProgressModel",
      "state": {
       "_dom_classes": [],
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "FloatProgressModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/controls",
       "_view_module_version": "2.0.0",
       "_view_name": "ProgressView",
       "bar_style": "success",
       "description": "",
       "description_allow_html": false,
       "layout": "IPY_MODEL_42faaa6dc73546939c8f6e178d7fd64b",
       "max": 211.0,
       "min": 0.0,
       "orientation": "horizontal",
       "style": "IPY_MODEL_6cac50ed751e4da8b7bd1f936be5f687",
       "tabbable": null,
       "tooltip": null,
       "value": 211.0
      }
     },
     "2c069abb5dfa414bbde130ae6532d054": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HTMLStyleModel",
      "state": {
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HTMLStyleModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "StyleView",
       "background": null,
       "description_width": "",
       "font_size": null,
       "text_color": null
      }
     },
     "2c78e4628fa34024b4d52de09624ec66": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "2.0.0",
      "model_name": "LayoutModel",
      "state": {
       "_model_module": "@jupyter-widgets/base",
       "_model_module_version": "2.0.0",
       "_model_name": "LayoutModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "LayoutView",
       "align_content": null,
       "align_items": null,
       "align_self": null,
       "border_bottom": null,
       "border_left": null,
       "border_right": null,
       "border_top": null,
       "bottom": null,
       "display": null,
       "flex": null,
       "flex_flow": null,
       "grid_area": null,
       "grid_auto_columns": null,
       "grid_auto_flow": null,
       "grid_auto_rows": null,
       "grid_column": null,
       "grid_gap": null,
       "grid_row": null,
       "grid_template_areas": null,
       "grid_template_columns": null,
       "grid_template_rows": null,
       "height": null,
       "justify_content": null,
       "justify_items": null,
       "left": null,
       "margin": null,
       "max_height": null,
       "max_width": null,
       "min_height": null,
       "min_width": null,
       "object_fit": null,
       "object_position": null,
       "order": null,
       "overflow": null,
       "padding": null,
       "right": null,
       "top": null,
       "visibility": null,
       "width": null
      }
     },
     "2e3b46f83739449791d9a021f0e573d6": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HTMLStyleModel",
      "state": {
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HTMLStyleModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "StyleView",
       "background": null,
       "description_width": "",
       "font_size": null,
       "text_color": null
      }
     },
     "350f66ddd51049d895ba5cb498fe2515": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HTMLStyleModel",
      "state": {
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HTMLStyleModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "StyleView",
       "background": null,
       "description_width": "",
       "font_size": null,
       "text_color": null
      }
     },
     "36ad3d22050b4960963e40127c468abf": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "2.0.0",
      "model_name": "LayoutModel",
      "state": {
       "_model_module": "@jupyter-widgets/base",
       "_model_module_version": "2.0.0",
       "_model_name": "LayoutModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "LayoutView",
       "align_content": null,
       "align_items": null,
       "align_self": null,
       "border_bottom": null,
       "border_left": null,
       "border_right": null,
       "border_top": null,
       "bottom": null,
       "display": null,
       "flex": null,
       "flex_flow": null,
       "grid_area": null,
       "grid_auto_columns": null,
       "grid_auto_flow": null,
       "grid_auto_rows": null,
       "grid_column": null,
       "grid_gap": null,
       "grid_row": null,
       "grid_template_areas": null,
       "grid_template_columns": null,
       "grid_template_rows": null,
       "height": null,
       "justify_content": null,
       "justify_items": null,
       "left": null,
       "margin": null,
       "max_height": null,
       "max_width": null,
       "min_height": null,
       "min_width": null,
       "object_fit": null,
       "object_position": null,
       "order": null,
       "overflow": null,
       "padding": null,
       "right": null,
       "top": null,
       "visibility": null,
       "width": null
      }
     },
     "382e43ef0d8347e7a56649ee35ebcf93": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "FloatProgressModel",
      "state": {
       "_dom_classes": [],
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "FloatProgressModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/controls",
       "_view_module_version": "2.0.0",
       "_view_name": "ProgressView",
       "bar_style": "success",
       "description": "",
       "description_allow_html": false,
       "layout": "IPY_MODEL_9893c23f2a50472f845cd3d48b892593",
       "max": 213.0,
       "min": 0.0,
       "orientation": "horizontal",
       "style": "IPY_MODEL_aec132acf9e24e55b5a26ad2f607e839",
       "tabbable": null,
       "tooltip": null,
       "value": 213.0
      }
     },
     "39dcc3bdcfa942949b2a178ccaf7cf6a": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HTMLModel",
      "state": {
       "_dom_classes": [],
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HTMLModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/controls",
       "_view_module_version": "2.0.0",
       "_view_name": "HTMLView",
       "description": "",
       "description_allow_html": false,
       "layout": "IPY_MODEL_36ad3d22050b4960963e40127c468abf",
       "placeholder": "​",
       "style": "IPY_MODEL_012e60fe92c441d1ab34f78af747a4b9",
       "tabbable": null,
       "tooltip": null,
       "value": " 211/211 [00:00&lt;00:00, 1109.12it/s, Materializing param=masked_spec_embed]"
      }
     },
     "3c50c8727126401fbac499758d354de3": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HTMLStyleModel",
      "state": {
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HTMLStyleModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "StyleView",
       "background": null,
       "description_width": "",
       "font_size": null,
       "text_color": null
      }
     },
     "3ce40239c4494b798531fd44beb4fb87": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HTMLStyleModel",
      "state": {
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HTMLStyleModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "StyleView",
       "background": null,
       "description_width": "",
       "font_size": null,
       "text_color": null
      }
     },
     "42faaa6dc73546939c8f6e178d7fd64b": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "2.0.0",
      "model_name": "LayoutModel",
      "state": {
       "_model_module": "@jupyter-widgets/base",
       "_model_module_version": "2.0.0",
       "_model_name": "LayoutModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "LayoutView",
       "align_content": null,
       "align_items": null,
       "align_self": null,
       "border_bottom": null,
       "border_left": null,
       "border_right": null,
       "border_top": null,
       "bottom": null,
       "display": null,
       "flex": null,
       "flex_flow": null,
       "grid_area": null,
       "grid_auto_columns": null,
       "grid_auto_flow": null,
       "grid_auto_rows": null,
       "grid_column": null,
       "grid_gap": null,
       "grid_row": null,
       "grid_template_areas": null,
       "grid_template_columns": null,
       "grid_template_rows": null,
       "height": null,
       "justify_content": null,
       "justify_items": null,
       "left": null,
       "margin": null,
       "max_height": null,
       "max_width": null,
       "min_height": null,
       "min_width": null,
       "object_fit": null,
       "object_position": null,
       "order": null,
       "overflow": null,
       "padding": null,
       "right": null,
       "top": null,
       "visibility": null,
       "width": null
      }
     },
     "5afb47cb39524d9d83517894d66ed0fe": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "2.0.0",
      "model_name": "LayoutModel",
      "state": {
       "_model_module": "@jupyter-widgets/base",
       "_model_module_version": "2.0.0",
       "_model_name": "LayoutModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "LayoutView",
       "align_content": null,
       "align_items": null,
       "align_self": null,
       "border_bottom": null,
       "border_left": null,
       "border_right": null,
       "border_top": null,
       "bottom": null,
       "display": null,
       "flex": null,
       "flex_flow": null,
       "grid_area": null,
       "grid_auto_columns": null,
       "grid_auto_flow": null,
       "grid_auto_rows": null,
       "grid_column": null,
       "grid_gap": null,
       "grid_row": null,
       "grid_template_areas": null,
       "grid_template_columns": null,
       "grid_template_rows": null,
       "height": null,
       "justify_content": null,
       "justify_items": null,
       "left": null,
       "margin": null,
       "max_height": null,
       "max_width": null,
       "min_height": null,
       "min_width": null,
       "object_fit": null,
       "object_position": null,
       "order": null,
       "overflow": null,
       "padding": null,
       "right": null,
       "top": null,
       "visibility": null,
       "width": null
      }
     },
     "5bb1898cf53e4e9ca2a82c76515cbf01": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HBoxModel",
      "state": {
       "_dom_classes": [],
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HBoxModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/controls",
       "_view_module_version": "2.0.0",
       "_view_name": "HBoxView",
       "box_style": "",
       "children": [
        "IPY_MODEL_5fd754fa264a4bffbe0246656a5eebf1",
        "IPY_MODEL_efe168d4791d4946aadb39043e79e29d",
        "IPY_MODEL_5eb29d3cf1b54904b1d009e1d65084b8"
       ],
       "layout": "IPY_MODEL_b125ff11363b4c21be68a944938d631d",
       "tabbable": null,
       "tooltip": null
      }
     },
     "5d32a0e05feb46f9a4aee780ce0c60b0": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HBoxModel",
      "state": {
       "_dom_classes": [],
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HBoxModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/controls",
       "_view_module_version": "2.0.0",
       "_view_name": "HBoxView",
       "box_style": "",
       "children": [
        "IPY_MODEL_606f4019152542b0be539c6d7b785404",
        "IPY_MODEL_1d58b7b4dd574e148a45db40bfa05ac7",
        "IPY_MODEL_39dcc3bdcfa942949b2a178ccaf7cf6a"
       ],
       "layout": "IPY_MODEL_b250e5b24fbf4a58bf2455169b98bdf2",
       "tabbable": null,
       "tooltip": null
      }
     },
     "5d9f870df1f64bb4b55099ddf4c411a1": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "2.0.0",
      "model_name": "LayoutModel",
      "state": {
       "_model_module": "@jupyter-widgets/base",
       "_model_module_version": "2.0.0",
       "_model_name": "LayoutModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "LayoutView",
       "align_content": null,
       "align_items": null,
       "align_self": null,
       "border_bottom": null,
       "border_left": null,
       "border_right": null,
       "border_top": null,
       "bottom": null,
       "display": null,
       "flex": null,
       "flex_flow": null,
       "grid_area": null,
       "grid_auto_columns": null,
       "grid_auto_flow": null,
       "grid_auto_rows": null,
       "grid_column": null,
       "grid_gap": null,
       "grid_row": null,
       "grid_template_areas": null,
       "grid_template_columns": null,
       "grid_template_rows": null,
       "height": null,
       "justify_content": null,
       "justify_items": null,
       "left": null,
       "margin": null,
       "max_height": null,
       "max_width": null,
       "min_height": null,
       "min_width": null,
       "object_fit": null,
       "object_position": null,
       "order": null,
       "overflow": null,
       "padding": null,
       "right": null,
       "top": null,
       "visibility": null,
       "width": null
      }
     },
     "5eb29d3cf1b54904b1d009e1d65084b8": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HTMLModel",
      "state": {
       "_dom_classes": [],
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HTMLModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/controls",
       "_view_module_version": "2.0.0",
       "_view_name": "HTMLView",
       "description": "",
       "description_allow_html": false,
       "layout": "IPY_MODEL_2c78e4628fa34024b4d52de09624ec66",
       "placeholder": "​",
       "style": "IPY_MODEL_a798af74a0ea47bb81d4bdb8684fa8f1",
       "tabbable": null,
       "tooltip": null,
       "value": " 378M/378M [00:01&lt;00:00, 367MB/s]"
      }
     },
     "5fd754fa264a4bffbe0246656a5eebf1": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HTMLModel",
      "state": {
       "_dom_classes": [],
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HTMLModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/controls",
       "_view_module_version": "2.0.0",
       "_view_name": "HTMLView",
       "description": "",
       "description_allow_html": false,
       "layout": "IPY_MODEL_068ae19c5332403590ab54780985df67",
       "placeholder": "​",
       "style": "IPY_MODEL_2e3b46f83739449791d9a021f0e573d6",
       "tabbable": null,
       "tooltip": null,
       "value": "model.safetensors: 100%"
      }
     },
     "606f4019152542b0be539c6d7b785404": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HTMLModel",
      "state": {
       "_dom_classes": [],
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HTMLModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/controls",
       "_view_module_version": "2.0.0",
       "_view_name": "HTMLView",
       "description": "",
       "description_allow_html": false,
       "layout": "IPY_MODEL_bc0993c1c9a34525a5208a9baafb6548",
       "placeholder": "​",
       "style": "IPY_MODEL_9d4e862b156d4c8dafaacbd3c2bd24c6",
       "tabbable": null,
       "tooltip": null,
       "value": "Loading weights: 100%"
      }
     },
     "658f2ac455c84d38aeedfb9552e6c5b1": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HBoxModel",
      "state": {
       "_dom_classes": [],
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HBoxModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/controls",
       "_view_module_version": "2.0.0",
       "_view_name": "HBoxView",
       "box_style": "",
       "children": [
        "IPY_MODEL_ec816d5c1b8c4e2abaa3d02ca89d555e",
        "IPY_MODEL_382e43ef0d8347e7a56649ee35ebcf93",
        "IPY_MODEL_9555f540b52e4b1d872347cedd745b34"
       ],
       "layout": "IPY_MODEL_b27140b34988444499fb32c6589af257",
       "tabbable": null,
       "tooltip": null
      }
     },
     "696e5a15578e4c28a58180fa4fb06a63": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HBoxModel",
      "state": {
       "_dom_classes": [],
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HBoxModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/controls",
       "_view_module_version": "2.0.0",
       "_view_name": "HBoxView",
       "box_style": "",
       "children": [
        "IPY_MODEL_0aa9b6ed35ab42708f124060d7a5d472",
        "IPY_MODEL_1c877983bd7e49109a9c1d489252b12e",
        "IPY_MODEL_a29f812510db401eb37075157eb5c4d7"
       ],
       "layout": "IPY_MODEL_0d6ad60046a248d7b1948f815f2d0cd1",
       "tabbable": null,
       "tooltip": null
      }
     },
     "6cac50ed751e4da8b7bd1f936be5f687": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "ProgressStyleModel",
      "state": {
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "ProgressStyleModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "StyleView",
       "bar_color": null,
       "description_width": ""
      }
     },
     "7cefb392af7a42f79429a080b30142a1": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "ProgressStyleModel",
      "state": {
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "ProgressStyleModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "StyleView",
       "bar_color": null,
       "description_width": ""
      }
     },
     "86ab85aa268446a59b27f4db34d80841": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "2.0.0",
      "model_name": "LayoutModel",
      "state": {
       "_model_module": "@jupyter-widgets/base",
       "_model_module_version": "2.0.0",
       "_model_name": "LayoutModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "LayoutView",
       "align_content": null,
       "align_items": null,
       "align_self": null,
       "border_bottom": null,
       "border_left": null,
       "border_right": null,
       "border_top": null,
       "bottom": null,
       "display": null,
       "flex": null,
       "flex_flow": null,
       "grid_area": null,
       "grid_auto_columns": null,
       "grid_auto_flow": null,
       "grid_auto_rows": null,
       "grid_column": null,
       "grid_gap": null,
       "grid_row": null,
       "grid_template_areas": null,
       "grid_template_columns": null,
       "grid_template_rows": null,
       "height": null,
       "justify_content": null,
       "justify_items": null,
       "left": null,
       "margin": null,
       "max_height": null,
       "max_width": null,
       "min_height": null,
       "min_width": null,
       "object_fit": null,
       "object_position": null,
       "order": null,
       "overflow": null,
       "padding": null,
       "right": null,
       "top": null,
       "visibility": null,
       "width": null
      }
     },
     "873fd82facb64266900fa62410e071e4": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "2.0.0",
      "model_name": "LayoutModel",
      "state": {
       "_model_module": "@jupyter-widgets/base",
       "_model_module_version": "2.0.0",
       "_model_name": "LayoutModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "LayoutView",
       "align_content": null,
       "align_items": null,
       "align_self": null,
       "border_bottom": null,
       "border_left": null,
       "border_right": null,
       "border_top": null,
       "bottom": null,
       "display": null,
       "flex": null,
       "flex_flow": null,
       "grid_area": null,
       "grid_auto_columns": null,
       "grid_auto_flow": null,
       "grid_auto_rows": null,
       "grid_column": null,
       "grid_gap": null,
       "grid_row": null,
       "grid_template_areas": null,
       "grid_template_columns": null,
       "grid_template_rows": null,
       "height": null,
       "justify_content": null,
       "justify_items": null,
       "left": null,
       "margin": null,
       "max_height": null,
       "max_width": null,
       "min_height": null,
       "min_width": null,
       "object_fit": null,
       "object_position": null,
       "order": null,
       "overflow": null,
       "padding": null,
       "right": null,
       "top": null,
       "visibility": null,
       "width": null
      }
     },
     "8ace722d24e146dcbe449a44cf9e11ba": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HTMLModel",
      "state": {
       "_dom_classes": [],
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HTMLModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/controls",
       "_view_module_version": "2.0.0",
       "_view_name": "HTMLView",
       "description": "",
       "description_allow_html": false,
       "layout": "IPY_MODEL_86ab85aa268446a59b27f4db34d80841",
       "placeholder": "​",
       "style": "IPY_MODEL_3c50c8727126401fbac499758d354de3",
       "tabbable": null,
       "tooltip": null,
       "value": " 1.39k/? [00:00&lt;00:00, 145kB/s]"
      }
     },
     "8b70f6df149f44a7899082a89d2079bc": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "ProgressStyleModel",
      "state": {
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "ProgressStyleModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "StyleView",
       "bar_color": null,
       "description_width": ""
      }
     },
     "8e949a9d9e714818880bcb5dcde3a94a": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "2.0.0",
      "model_name": "LayoutModel",
      "state": {
       "_model_module": "@jupyter-widgets/base",
       "_model_module_version": "2.0.0",
       "_model_name": "LayoutModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "LayoutView",
       "align_content": null,
       "align_items": null,
       "align_self": null,
       "border_bottom": null,
       "border_left": null,
       "border_right": null,
       "border_top": null,
       "bottom": null,
       "display": null,
       "flex": null,
       "flex_flow": null,
       "grid_area": null,
       "grid_auto_columns": null,
       "grid_auto_flow": null,
       "grid_auto_rows": null,
       "grid_column": null,
       "grid_gap": null,
       "grid_row": null,
       "grid_template_areas": null,
       "grid_template_columns": null,
       "grid_template_rows": null,
       "height": null,
       "justify_content": null,
       "justify_items": null,
       "left": null,
       "margin": null,
       "max_height": null,
       "max_width": null,
       "min_height": null,
       "min_width": null,
       "object_fit": null,
       "object_position": null,
       "order": null,
       "overflow": null,
       "padding": null,
       "right": null,
       "top": null,
       "visibility": null,
       "width": null
      }
     },
     "9555f540b52e4b1d872347cedd745b34": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HTMLModel",
      "state": {
       "_dom_classes": [],
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HTMLModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/controls",
       "_view_module_version": "2.0.0",
       "_view_name": "HTMLView",
       "description": "",
       "description_allow_html": false,
       "layout": "IPY_MODEL_873fd82facb64266900fa62410e071e4",
       "placeholder": "​",
       "style": "IPY_MODEL_d9fe0fabd265457bae70e18b0328fc29",
       "tabbable": null,
       "tooltip": null,
       "value": " 213/213 [00:00&lt;00:00, 21.3kB/s]"
      }
     },
     "97d35f48436f4c9cac4d75b1dbb64201": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HTMLModel",
      "state": {
       "_dom_classes": [],
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HTMLModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/controls",
       "_view_module_version": "2.0.0",
       "_view_name": "HTMLView",
       "description": "",
       "description_allow_html": false,
       "layout": "IPY_MODEL_1966f6ac24e54cf78ef5b7c0b1e3c99e",
       "placeholder": "​",
       "style": "IPY_MODEL_350f66ddd51049d895ba5cb498fe2515",
       "tabbable": null,
       "tooltip": null,
       "value": "config.json: "
      }
     },
     "9893c23f2a50472f845cd3d48b892593": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "2.0.0",
      "model_name": "LayoutModel",
      "state": {
       "_model_module": "@jupyter-widgets/base",
       "_model_module_version": "2.0.0",
       "_model_name": "LayoutModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "LayoutView",
       "align_content": null,
       "align_items": null,
       "align_self": null,
       "border_bottom": null,
       "border_left": null,
       "border_right": null,
       "border_top": null,
       "bottom": null,
       "display": null,
       "flex": null,
       "flex_flow": null,
       "grid_area": null,
       "grid_auto_columns": null,
       "grid_auto_flow": null,
       "grid_auto_rows": null,
       "grid_column": null,
       "grid_gap": null,
       "grid_row": null,
       "grid_template_areas": null,
       "grid_template_columns": null,
       "grid_template_rows": null,
       "height": null,
       "justify_content": null,
       "justify_items": null,
       "left": null,
       "margin": null,
       "max_height": null,
       "max_width": null,
       "min_height": null,
       "min_width": null,
       "object_fit": null,
       "object_position": null,
       "order": null,
       "overflow": null,
       "padding": null,
       "right": null,
       "top": null,
       "visibility": null,
       "width": null
      }
     },
     "9d4e862b156d4c8dafaacbd3c2bd24c6": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HTMLStyleModel",
      "state": {
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HTMLStyleModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "StyleView",
       "background": null,
       "description_width": "",
       "font_size": null,
       "text_color": null
      }
     },
     "a29f812510db401eb37075157eb5c4d7": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HTMLModel",
      "state": {
       "_dom_classes": [],
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HTMLModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/controls",
       "_view_module_version": "2.0.0",
       "_view_name": "HTMLView",
       "description": "",
       "description_allow_html": false,
       "layout": "IPY_MODEL_5d9f870df1f64bb4b55099ddf4c411a1",
       "placeholder": "​",
       "style": "IPY_MODEL_3ce40239c4494b798531fd44beb4fb87",
       "tabbable": null,
       "tooltip": null,
       "value": " 378M/378M [00:01&lt;00:00, 508MB/s]"
      }
     },
     "a798af74a0ea47bb81d4bdb8684fa8f1": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HTMLStyleModel",
      "state": {
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HTMLStyleModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "StyleView",
       "background": null,
       "description_width": "",
       "font_size": null,
       "text_color": null
      }
     },
     "aec132acf9e24e55b5a26ad2f607e839": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "ProgressStyleModel",
      "state": {
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "ProgressStyleModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "StyleView",
       "bar_color": null,
       "description_width": ""
      }
     },
     "b125ff11363b4c21be68a944938d631d": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "2.0.0",
      "model_name": "LayoutModel",
      "state": {
       "_model_module": "@jupyter-widgets/base",
       "_model_module_version": "2.0.0",
       "_model_name": "LayoutModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "LayoutView",
       "align_content": null,
       "align_items": null,
       "align_self": null,
       "border_bottom": null,
       "border_left": null,
       "border_right": null,
       "border_top": null,
       "bottom": null,
       "display": null,
       "flex": null,
       "flex_flow": null,
       "grid_area": null,
       "grid_auto_columns": null,
       "grid_auto_flow": null,
       "grid_auto_rows": null,
       "grid_column": null,
       "grid_gap": null,
       "grid_row": null,
       "grid_template_areas": null,
       "grid_template_columns": null,
       "grid_template_rows": null,
       "height": null,
       "justify_content": null,
       "justify_items": null,
       "left": null,
       "margin": null,
       "max_height": null,
       "max_width": null,
       "min_height": null,
       "min_width": null,
       "object_fit": null,
       "object_position": null,
       "order": null,
       "overflow": null,
       "padding": null,
       "right": null,
       "top": null,
       "visibility": null,
       "width": null
      }
     },
     "b250e5b24fbf4a58bf2455169b98bdf2": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "2.0.0",
      "model_name": "LayoutModel",
      "state": {
       "_model_module": "@jupyter-widgets/base",
       "_model_module_version": "2.0.0",
       "_model_name": "LayoutModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "LayoutView",
       "align_content": null,
       "align_items": null,
       "align_self": null,
       "border_bottom": null,
       "border_left": null,
       "border_right": null,
       "border_top": null,
       "bottom": null,
       "display": null,
       "flex": null,
       "flex_flow": null,
       "grid_area": null,
       "grid_auto_columns": null,
       "grid_auto_flow": null,
       "grid_auto_rows": null,
       "grid_column": null,
       "grid_gap": null,
       "grid_row": null,
       "grid_template_areas": null,
       "grid_template_columns": null,
       "grid_template_rows": null,
       "height": null,
       "justify_content": null,
       "justify_items": null,
       "left": null,
       "margin": null,
       "max_height": null,
       "max_width": null,
       "min_height": null,
       "min_width": null,
       "object_fit": null,
       "object_position": null,
       "order": null,
       "overflow": null,
       "padding": null,
       "right": null,
       "top": null,
       "visibility": null,
       "width": null
      }
     },
     "b27140b34988444499fb32c6589af257": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "2.0.0",
      "model_name": "LayoutModel",
      "state": {
       "_model_module": "@jupyter-widgets/base",
       "_model_module_version": "2.0.0",
       "_model_name": "LayoutModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "LayoutView",
       "align_content": null,
       "align_items": null,
       "align_self": null,
       "border_bottom": null,
       "border_left": null,
       "border_right": null,
       "border_top": null,
       "bottom": null,
       "display": null,
       "flex": null,
       "flex_flow": null,
       "grid_area": null,
       "grid_auto_columns": null,
       "grid_auto_flow": null,
       "grid_auto_rows": null,
       "grid_column": null,
       "grid_gap": null,
       "grid_row": null,
       "grid_template_areas": null,
       "grid_template_columns": null,
       "grid_template_rows": null,
       "height": null,
       "justify_content": null,
       "justify_items": null,
       "left": null,
       "margin": null,
       "max_height": null,
       "max_width": null,
       "min_height": null,
       "min_width": null,
       "object_fit": null,
       "object_position": null,
       "order": null,
       "overflow": null,
       "padding": null,
       "right": null,
       "top": null,
       "visibility": null,
       "width": null
      }
     },
     "bc0993c1c9a34525a5208a9baafb6548": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "2.0.0",
      "model_name": "LayoutModel",
      "state": {
       "_model_module": "@jupyter-widgets/base",
       "_model_module_version": "2.0.0",
       "_model_name": "LayoutModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "LayoutView",
       "align_content": null,
       "align_items": null,
       "align_self": null,
       "border_bottom": null,
       "border_left": null,
       "border_right": null,
       "border_top": null,
       "bottom": null,
       "display": null,
       "flex": null,
       "flex_flow": null,
       "grid_area": null,
       "grid_auto_columns": null,
       "grid_auto_flow": null,
       "grid_auto_rows": null,
       "grid_column": null,
       "grid_gap": null,
       "grid_row": null,
       "grid_template_areas": null,
       "grid_template_columns": null,
       "grid_template_rows": null,
       "height": null,
       "justify_content": null,
       "justify_items": null,
       "left": null,
       "margin": null,
       "max_height": null,
       "max_width": null,
       "min_height": null,
       "min_width": null,
       "object_fit": null,
       "object_position": null,
       "order": null,
       "overflow": null,
       "padding": null,
       "right": null,
       "top": null,
       "visibility": null,
       "width": null
      }
     },
     "c81308bc3c5e48508a0eefcd8bbe2032": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "2.0.0",
      "model_name": "LayoutModel",
      "state": {
       "_model_module": "@jupyter-widgets/base",
       "_model_module_version": "2.0.0",
       "_model_name": "LayoutModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "LayoutView",
       "align_content": null,
       "align_items": null,
       "align_self": null,
       "border_bottom": null,
       "border_left": null,
       "border_right": null,
       "border_top": null,
       "bottom": null,
       "display": null,
       "flex": null,
       "flex_flow": null,
       "grid_area": null,
       "grid_auto_columns": null,
       "grid_auto_flow": null,
       "grid_auto_rows": null,
       "grid_column": null,
       "grid_gap": null,
       "grid_row": null,
       "grid_template_areas": null,
       "grid_template_columns": null,
       "grid_template_rows": null,
       "height": null,
       "justify_content": null,
       "justify_items": null,
       "left": null,
       "margin": null,
       "max_height": null,
       "max_width": null,
       "min_height": null,
       "min_width": null,
       "object_fit": null,
       "object_position": null,
       "order": null,
       "overflow": null,
       "padding": null,
       "right": null,
       "top": null,
       "visibility": null,
       "width": null
      }
     },
     "c85fa0d3c14f41febebbd370c9afbc0a": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "ProgressStyleModel",
      "state": {
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "ProgressStyleModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "StyleView",
       "bar_color": null,
       "description_width": ""
      }
     },
     "d9fe0fabd265457bae70e18b0328fc29": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HTMLStyleModel",
      "state": {
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HTMLStyleModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "StyleView",
       "background": null,
       "description_width": "",
       "font_size": null,
       "text_color": null
      }
     },
     "da531c7308bd47f4af5c8aa32f0e1ed5": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "2.0.0",
      "model_name": "LayoutModel",
      "state": {
       "_model_module": "@jupyter-widgets/base",
       "_model_module_version": "2.0.0",
       "_model_name": "LayoutModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "LayoutView",
       "align_content": null,
       "align_items": null,
       "align_self": null,
       "border_bottom": null,
       "border_left": null,
       "border_right": null,
       "border_top": null,
       "bottom": null,
       "display": null,
       "flex": null,
       "flex_flow": null,
       "grid_area": null,
       "grid_auto_columns": null,
       "grid_auto_flow": null,
       "grid_auto_rows": null,
       "grid_column": null,
       "grid_gap": null,
       "grid_row": null,
       "grid_template_areas": null,
       "grid_template_columns": null,
       "grid_template_rows": null,
       "height": null,
       "justify_content": null,
       "justify_items": null,
       "left": null,
       "margin": null,
       "max_height": null,
       "max_width": null,
       "min_height": null,
       "min_width": null,
       "object_fit": null,
       "object_position": null,
       "order": null,
       "overflow": null,
       "padding": null,
       "right": null,
       "top": null,
       "visibility": null,
       "width": null
      }
     },
     "db417a9bf01e4ae9a9d419b88f55d497": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HBoxModel",
      "state": {
       "_dom_classes": [],
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HBoxModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/controls",
       "_view_module_version": "2.0.0",
       "_view_name": "HBoxView",
       "box_style": "",
       "children": [
        "IPY_MODEL_97d35f48436f4c9cac4d75b1dbb64201",
        "IPY_MODEL_e4577bf34ac248ad853571a8177a0a48",
        "IPY_MODEL_8ace722d24e146dcbe449a44cf9e11ba"
       ],
       "layout": "IPY_MODEL_8e949a9d9e714818880bcb5dcde3a94a",
       "tabbable": null,
       "tooltip": null
      }
     },
     "e4577bf34ac248ad853571a8177a0a48": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "FloatProgressModel",
      "state": {
       "_dom_classes": [],
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "FloatProgressModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/controls",
       "_view_module_version": "2.0.0",
       "_view_name": "ProgressView",
       "bar_style": "success",
       "description": "",
       "description_allow_html": false,
       "layout": "IPY_MODEL_05bbd17994084c1995de3afe28122a29",
       "max": 1.0,
       "min": 0.0,
       "orientation": "horizontal",
       "style": "IPY_MODEL_8b70f6df149f44a7899082a89d2079bc",
       "tabbable": null,
       "tooltip": null,
       "value": 1.0
      }
     },
     "ec816d5c1b8c4e2abaa3d02ca89d555e": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HTMLModel",
      "state": {
       "_dom_classes": [],
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HTMLModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/controls",
       "_view_module_version": "2.0.0",
       "_view_name": "HTMLView",
       "description": "",
       "description_allow_html": false,
       "layout": "IPY_MODEL_efec2d8ae7c543898c73ec24ff49eb54",
       "placeholder": "​",
       "style": "IPY_MODEL_ed0b17574ba641bf89ab3a90b9d73ef0",
       "tabbable": null,
       "tooltip": null,
       "value": "preprocessor_config.json: 100%"
      }
     },
     "ed0b17574ba641bf89ab3a90b9d73ef0": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "HTMLStyleModel",
      "state": {
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "HTMLStyleModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "StyleView",
       "background": null,
       "description_width": "",
       "font_size": null,
       "text_color": null
      }
     },
     "efe168d4791d4946aadb39043e79e29d": {
      "model_module": "@jupyter-widgets/controls",
      "model_module_version": "2.0.0",
      "model_name": "FloatProgressModel",
      "state": {
       "_dom_classes": [],
       "_model_module": "@jupyter-widgets/controls",
       "_model_module_version": "2.0.0",
       "_model_name": "FloatProgressModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/controls",
       "_view_module_version": "2.0.0",
       "_view_name": "ProgressView",
       "bar_style": "success",
       "description": "",
       "description_allow_html": false,
       "layout": "IPY_MODEL_c81308bc3c5e48508a0eefcd8bbe2032",
       "max": 377510580.0,
       "min": 0.0,
       "orientation": "horizontal",
       "style": "IPY_MODEL_7cefb392af7a42f79429a080b30142a1",
       "tabbable": null,
       "tooltip": null,
       "value": 377510580.0
      }
     },
     "efec2d8ae7c543898c73ec24ff49eb54": {
      "model_module": "@jupyter-widgets/base",
      "model_module_version": "2.0.0",
      "model_name": "LayoutModel",
      "state": {
       "_model_module": "@jupyter-widgets/base",
       "_model_module_version": "2.0.0",
       "_model_name": "LayoutModel",
       "_view_count": null,
       "_view_module": "@jupyter-widgets/base",
       "_view_module_version": "2.0.0",
       "_view_name": "LayoutView",
       "align_content": null,
       "align_items": null,
       "align_self": null,
       "border_bottom": null,
       "border_left": null,
       "border_right": null,
       "border_top": null,
       "bottom": null,
       "display": null,
       "flex": null,
       "flex_flow": null,
       "grid_area": null,
       "grid_auto_columns": null,
       "grid_auto_flow": null,
       "grid_auto_rows": null,
       "grid_column": null,
       "grid_gap": null,
       "grid_row": null,
       "grid_template_areas": null,
       "grid_template_columns": null,
       "grid_template_rows": null,
       "height": null,
       "justify_content": null,
       "justify_items": null,
       "left": null,
       "margin": null,
       "max_height": null,
       "max_width": null,
       "min_height": null,
       "min_width": null,
       "object_fit": null,
       "object_position": null,
       "order": null,
       "overflow": null,
       "padding": null,
       "right": null,
       "top": null,
       "visibility": null,
       "width": null
      }
     }
    },
    "version_major": 2,
    "version_minor": 0
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
